### ISSUE TITLE
运行报循环引用错误.

### ISSUE THREAD

**Issue by shenguanjiejie** [1111mp/im_server#21]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/9425605/236660198-bdf07553-9385-407c-9586-94b42841c779.png">
node : v16.19.1

**Comment by 1111mp** [comment]
@shenguanjiejie 重新拉一下代码试试呢 这个是代码语法错误引起的 代码本地很早就改了 但是没有推到github上来 不好意思啊

**Comment by shenguanjiejie** [comment]
哈哈 没关系, 这个问题好了, 还有点其他问题. 必须要依赖本地redis么?
<img width="899" alt="image" src="https://user-images.githubusercontent.com/9425605/236977050-43dc5886-ea67-4c31-a38e-5811c8dce647.png">

**Comment by 1111mp** [comment]
是的，缓存相关的都是用的redis，包括bull的队列也是基于redis。这张截图报错应该是数据库连接的问题。

**Comment by shenguanjiejie** [comment]
redis 可以了, 这是要连接sqlite么? 失败了.
<img width="1281" alt="image" src="https://github.com/1111mp/im_server/assets/9425605/d542326f-0bc1-4ef9-bd51-9e5ccb68bbed">
<img width="554" alt="image" src="https://github.com/1111mp/im_server/assets/9425605/097de6c1-547e-4c6b-baf7-8d79af7e5605">

**Comment by 1111mp** [comment]
我用的mariadb，你得安装一下

**Comment by shenguanjiejie** [comment]
OK, 这里应该也需要改一下, 我就不提PR了, 你直接改一下好了.
<img width="718" alt="image" src="https://github.com/1111mp/im_server/assets/9425605/4bd4dfb0-dee3-4be6-a615-bb6d6ca68527">

**Comment by 1111mp** [comment]
这里你可以看nestjs的文档：https://docs.nestjs.cn/9/security?id=%e5%ae%9e%e7%8e%b0-passport-jwt
json web token.
passport-jwt 库的 jwtFromRequest 选项目前不支持异步函数，解决方案参考：https://github.com/mikenicholson/passport-jwt/pull/187

**Comment by shenguanjiejie** [comment]
嗯嗯 好的 那我把issue关闭了哈.
